### ISSUE TITLE
Whisper with no message

### ISSUE THREAD

**Issue by WilbertBegemann** [matthewdavidkeys/no-connection#10]
"@username"

spits out an error 
Exception in thread "Thread-0" java.lang.StringIndexOutOfBoundsException: begin 1, end -1, length 5
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3751)
	at java.base/java.lang.String.substring(String.java:1907)
	at ClientThread.run(ClientThread.java:128)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by matthewdavidkeys** [comment]
Thank you, will get on this soon

**Comment by liam-barkley** [comment]
this should be fixed
