### ISSUE TITLE
whisper only @ breaks

### ISSUE THREAD

**Issue by WilbertBegemann** [matthewdavidkeys/no-connection#15]
the @ breaks spits out error
@matthewdavidkeys
Exception in thread "Thread-0" java.lang.StringIndexOutOfBoundsException: begin 1, end -1, length 1
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at ClientThread.run(ClientThread.java:161)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by liam-barkley** [comment]
on this

**Comment by liam-barkley** [comment]
should be resolved now
