### ISSUE TITLE
server error after wisper self message

### ISSUE THREAD

**Issue by WilbertBegemann** [matthewdavidkeys/no-connection#16]
1. client1 joins
2. other client2 joins
3.  client1 sends @client2 hello
4. client2 sends @client1 hello
5. client1 leaves
6. client3 joins with client1 as name
7. client3 sends @client2 hi
8. client3 leaves
9. client2 @client2 hi

server error
Exception in thread "Thread-2" java.lang.StringIndexOutOfBoundsException: begin 1, end -1, length 5
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at ClientThread.run(ClientThread.java:161)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by liam-barkley** [comment]
can you recheck and see if this is still an issue please?

**Comment by WilbertBegemann** [comment]
works now ty
